blank_issues_enabled: true
contact_links:
  - name: Question or discussion
    url: https://github.com/CommunityToolkit/dotnet/discussions/new
    about: I have a question about how to use something in the toolkit
  - name: Documentation
    url: https://github.com/MicrosoftDocs/CommunityToolkit/issues/new
    about: I have a documentation suggestion or question